import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

    // But you can create a sidebar manually

    tutorialSidebar: [
        'intro',
        'getting-started',
        'architecture',
        'attestation',

        // --- Added integrations category ---
        {
            type: 'category',
            label: 'Integrations',
            items: [
                'integrations/continue',
                'integrations/opencode',
            ],
        },

        // --- Added developer guide category ---
        {
            type: 'category',
            label: 'Developer Guide',
            items: [
                'developer-guide/index',
                'developer-guide/open-webui',
                'developer-guide/private-model-upload',
                'developer-guide/hal',
                'developer-guide/fine-tuning',
            ],
        },
    ],
};

export default sidebars;
